# Default values for tce-all-in-one.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

host: nowhere.com

acme:
  # acme issuer type (staging | production)
  environment: staging

image:
  repository: nobody
  tag: main

replicas: 1

containerPorts:
  http: 3000

ports:
  http: 80

env:
  AUTH0_AUDIENCE: "AUTH0_AUDIENCE"
  AUTH0_ISSUER_URL: "AUTH0_ISSUER_URL"
  PRIVATE_KEY: "PRIVATE_KEY"
  TOPOS_SUBNET_ENDPOINT: "TOPOS_SUBNET_ENDPOINT"
  SUBNET_REGISTRATOR_CONTRACT_ADDRESS: "SUBNET_REGISTRATOR_CONTRACT_ADDRESS"
  TOPOS_CORE_PROXY_CONTRACT_ADDRESS: "TOPOS_CORE_PROXY_CONTRACT_ADDRESS"
  TRACING_OTEL_COLLECTOR_ENDPOINT: "TRACING_OTEL_COLLECTOR_ENDPOINT"
