apiVersion: v1
kind: Service
metadata:
  name: executor-service
  labels:
    app: executor-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app: executor-service
  sessionAffinity: ClientIP
