apiVersion: v1
kind: Service
metadata:
  name: executor-service
  labels:
    app: executor-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: http
      protocol: TCP
    - name: otlp-receiver
      port: 4318
      targetPort: otlp-receiver
      protocol: TCP
    - name: prom-exporter
      port: 8889
      targetPort: prom-exporter
      protocol: TCP
  selector:
    app: executor-service
  sessionAffinity: ClientIP
