apiVersion: v1
kind: Pod
metadata:
  name: executor-service
  labels:
    app: executor-service
spec:
  restartPolicy: Always
  containers:
    - name: executor-service
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: Always
      ports:
        - name: http
          containerPort: {{ .Values.containerPorts.http }}
      env:
        - name: AUTH0_AUDIENCE
          value: {{ .Values.env.AUTH0_AUDIENCE }}
        - name: AUTH0_ISSUER_URL
          value: {{ .Values.env.AUTH0_ISSUER_URL }}
        - name: PRIVATE_KEY
          value: {{ .Values.env.PRIVATE_KEY }}
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: TOPOS_SUBNET_ENDPOINT
          value: {{ .Values.env.TOPOS_SUBNET_ENDPOINT }}
        - name: SUBNET_REGISTRATOR_CONTRACT_ADDRESS
          value: {{ .Values.env.SUBNET_REGISTRATOR_CONTRACT_ADDRESS }}
        - name: TOPOS_CORE_CONTRACT_ADDRESS
          value: {{ .Values.env.TOPOS_CORE_CONTRACT_ADDRESS }}
        - name: TRACING_OTEL_COLLECTOR_ENDPOINT
          value: {{ .Values.env.TRACING_OTEL_COLLECTOR_ENDPOINT }}
