apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor-service
  labels:
    app: executor-service
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: executor-service
  template:
    metadata:
      labels:
        app: executor-service
    spec:
      restartPolicy: Always
      containers:
        - name: executor-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
          env:
            - name: AUTH0_AUDIENCE
              value: {{ .Values.env.AUTH0_AUDIENCE }}
            - name: AUTH0_ISSUER_URL
              value: {{ .Values.env.AUTH0_ISSUER_URL }}
            - name: PRIVATE_KEY
              value: {{ .Values.env.PRIVATE_KEY }}
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: TOPOS_SUBNET_ENDPOINT
              value: {{ .Values.env.TOPOS_SUBNET_ENDPOINT }}
            - name: SUBNET_REGISTRATOR_CONTRACT_ADDRESS
              value: {{ .Values.env.SUBNET_REGISTRATOR_CONTRACT_ADDRESS }}
            - name: TOPOS_CORE_PROXY_CONTRACT_ADDRESS
              value: {{ .Values.env.TOPOS_CORE_PROXY_CONTRACT_ADDRESS }}
            - name: ELASTIC_APM_ENDPOINT
              value: {{ .Values.env.ELASTIC_APM_ENDPOINT }}
            - name: ELASTIC_APM_TOKEN
              value: {{ .Values.env.ELASTIC_APM_TOKEN }}
