apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor-service
  labels:
    app: executor-service
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: executor-service
  template:
    metadata:
      labels:
        app: executor-service
    spec:
      restartPolicy: Always
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.88.0
          ports:
            - name: otlp-receiver
              containerPort: 4318
            - name: prom-exporter
              containerPort: 8889
          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /etc/otelcol-contrib
        - name: executor-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
          env:
            - name: AUTH0_AUDIENCE
              value: {{ .Values.env.AUTH0_AUDIENCE }}
            - name: AUTH0_ISSUER_URL
              value: {{ .Values.env.AUTH0_ISSUER_URL }}
            - name: PRIVATE_KEY
              value: {{ .Values.env.PRIVATE_KEY }}
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: TOPOS_SUBNET_ENDPOINT
              value: {{ .Values.env.TOPOS_SUBNET_ENDPOINT }}
            - name: SUBNET_REGISTRATOR_CONTRACT_ADDRESS
              value: {{ .Values.env.SUBNET_REGISTRATOR_CONTRACT_ADDRESS }}
            - name: TOPOS_CORE_PROXY_CONTRACT_ADDRESS
              value: {{ .Values.env.TOPOS_CORE_PROXY_CONTRACT_ADDRESS }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.env.OTEL_SERVICE_NAME }}
            - name: OTEL_SERVICE_VERSION
              value: {{ .Values.env.OTEL_SERVICE_VERSION }}
      volumes:
        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: config.yaml
          name: otel-collector-config-vol
