apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  restartPolicy: Always
  containers:
    - name: redis
      image: redis/redis-stack-server:latest
      imagePullPolicy: Always
      ports:
        - name: http
          containerPort: 6379
