apiVersion: v1
kind: Service
metadata:
  name: dapp-frontend-erc20
  labels:
    app: dapp-frontend-erc20
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app: dapp-frontend-erc20
  sessionAffinity: ClientIP
