---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dapp-frontend-erc20-otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
            cors:
              allowed_origins: ["https://{{ .Values.host }}"]

    exporters:
      otlphttp:
        endpoint: {{ .Values.telemetry.exporters.otlphttp.endpoint }}
        
    processors:
      batch:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
      telemetry:
        logs:
          level: "{{ .Values.telemetry.logs.level }}"
