apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapp-frontend-erc20
  labels:
    app: dapp-frontend-erc20
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapp-frontend-erc20
  template:
    metadata:
      labels:
        app: dapp-frontend-erc20
    spec:
      restartPolicy: Always
      containers:
        - name: dapp-frontend-erc20
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
          env:
            - name: AUTH0_AUDIENCE
              value: {{ .Values.env.AUTH0_AUDIENCE }}
            - name: AUTH0_CLIENT_ID
              value: {{ .Values.env.AUTH0_CLIENT_ID }}
            - name: AUTH0_CLIENT_SECRET
              value: {{ .Values.env.AUTH0_CLIENT_SECRET }}
            - name: AUTH0_ISSUER_URL
              value: {{ .Values.env.AUTH0_ISSUER_URL }}
            - name: TRACING_OTEL_COLLECTOR_ENDPOINT
              value: {{ .Values.env.TRACING_OTEL_COLLECTOR_ENDPOINT }}
