apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dapp-frontend-erc20
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-{{ .Values.acme.environment }}"
spec:
  ingressClassName: "{{ .Values.ingress.class }}"
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: "{{ .Values.host }}-secret-tls"
    - hosts:
        - {{ .Values.telemetry.receivers.otlp.host }}
      secretName: "{{ .Values.telemetry.receivers.otlp.host }}-secret-tls"
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dapp-frontend-erc20
                port:
                  name: http
    - host: {{ .Values.telemetry.receivers.otlp.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dapp-frontend-erc20
                port:
                  name: otlp-receiver
