# Default values for tce-all-in-one.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

host: nowhere.com

acme:
  environment: staging

image:
  repository: nobody
  tag: main

containerPorts:
  http: 80

ports:
  http: 80
