# Default values for tce-all-in-one.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

host: nowhere.com

acme:
  # acme issuer type (staging | production)
  environment: staging

image:
  repository: nobody
  tag: main

containerPorts:
  http: 3000

ports:
  http: 80

ingress:
  class:
    faucet: nginx
    prometheusExporter: nginx

telemetry:
  exporters:
    otlphttp: 
      endpoint: nobody
    prometheus:
      host: nobody
  logs:
    level: info
  receivers:
    otlp:
      host: nobody # used for the ingress

env:
  OTEL_EXPORTER_OTLP_ENDPOINT: "OTEL_EXPORTER_OTLP_ENDPOINT"
  OTEL_SERVICE_NAME: "OTEL_SERVICE_NAME"
  OTEL_SERVICE_VERSION: "OTEL_SERVICE_VERSION"
  PRIVATE_KEY: "PRIVATE_KEY"
  THROTTLER_TTL_SECONDS: "THROTTLER_TTL_SECONDS"
