apiVersion: apps/v1
kind: Deployment
metadata:
  name: faucet
  labels:
    app: faucet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faucet
  template:
    metadata:
      labels:
        app: faucet
    spec:
      restartPolicy: Always
      containers:
        - name: faucet
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
          env:
            - name: ELASTIC_APM_ENDPOINT
              value: {{ .Values.env.ELASTIC_APM_ENDPOINT }}
            - name: ELASTIC_APM_TOKEN
              value: {{ .Values.env.ELASTIC_APM_TOKEN }}
            - name: PRIVATE_KEY
              value: {{ .Values.env.PRIVATE_KEY }}
            - name: TRACING_SERVICE_NAME
              value: {{ .Values.env.TRACING_SERVICE_NAME }}
            - name: TRACING_SERVICE_VERSION
              value: {{ .Values.env.TRACING_SERVICE_VERSION }}
            - name: THROTTLER_TTL_SECONDS
              value: "{{ .Values.env.THROTTLER_TTL_SECONDS }}"
