apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: faucet
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
    cert-manager.io/cluster-issuer: "letsencrypt-{{ .Values.acme.environment }}"
spec:
  ingressClassName: "{{ .Values.ingress.class.faucet }}"
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: "{{ .Values.host }}-secret-tls"
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: faucet
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: faucet-otlp-receiver
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-{{ .Values.acme.environment }}"
spec:
  ingressClassName: "{{ .Values.ingress.class.faucet }}"
  tls:
    - hosts:
        - {{ .Values.telemetry.receivers.otlp.host }}
      secretName: "{{ .Values.telemetry.receivers.otlp.host }}-secret-tls"
  rules:
    - host: {{ .Values.telemetry.receivers.otlp.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: faucet
                port:
                  name: otlp-receiver
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: faucet-prometheus
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-{{ .Values.acme.environment }}"
spec:
  ingressClassName: "{{ .Values.ingress.class.prometheusExporter }}"
  tls:
    - hosts:
        - {{ .Values.telemetry.exporters.prometheus.host }}
      secretName: "{{ .Values.telemetry.exporters.prometheus.host }}-secret-tls"
  rules:
    - host: {{ .Values.telemetry.exporters.prometheus.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: faucet
                port:
                  name: prom-exporter
