apiVersion: v1
kind: Service
metadata:
  name: explorer
  labels:
    app: explorer
spec:
  type: ClusterIP
  ports:
    - name: http
      port: { { $.Values.ports.http } }
      targetPort: http
      protocol: TCP
  selector:
    app: explorer
  sessionAffinity: ClientIP
