apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Values.mode }}
  labels:
    app: {{ $.Values.mode }}
    stack: tce
spec:
  serviceName: tce
  podManagementPolicy: "Parallel"
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: {{ $.Values.mode }}
      stack: tce
  template:
    metadata:
      labels:
        app: {{ $.Values.mode }}
        stack: tce
    spec:
      serviceAccountName: s3-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload
                operator: In
                values:
                - topos
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "topos"
          effect: "NoExecute"
      containers:
        - name: {{ $.Values.mode }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: Always
          command: ["topos"]
          args: ["node", "up", "--name", "$(HOSTNAME)", "--no-edge-process"]
          # command: ["/bin/sh","-c"]
          # args: ["tail -f /dev/null"]
          volumeMounts:
            - mountPath: /data/node/
              name: data
            - mountPath: /data/subnet/topos/
              name: shared
          env:
            - name: TOPOS_HOME
              value: /data/
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: grpc
              containerPort: {{ $.Values.ports.grpc }}
              protocol: TCP
            - name: p2p
              containerPort: {{ $.Values.ports.p2p }}
              protocol: TCP
            - name: graphql
              containerPort: {{ $.Values.ports.graphql }}
              protocol: TCP
            - name: metrics
              containerPort: {{ $.Values.ports.metrics }}
              protocol: TCP
      initContainers:
        - name: init
          image: amazon/aws-cli:latest
          command: ["/bin/sh","-c"]
          args: ["rm -rf /data/node/${HOSTNAME} || true; aws s3 cp s3://bnet-268276581508/genesis.json /data/subnet/topos/; aws s3 cp --recursive s3://bnet-268276581508/node/${HOSTNAME} /data/node/${HOSTNAME}"]
          volumeMounts:
            - mountPath: /data/node/
              name: data
            - mountPath: /data/subnet/topos/
              name: shared
      volumes:
      - name: shared
        persistentVolumeClaim:
          claimName: shared
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOncePod" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 1Gi
