{{ $sa := lookup "v1" "ServiceAccount" .Release.Namespace "s3-sa" }}
{{ if not $sa }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ $.Values.s3.role }}
  name: s3-sa
{{ end }}
---
{{ $svc := lookup "v1" "Service" .Release.Namespace "tce" }}
{{ if not $svc }}
apiVersion: v1
kind: Service
metadata:
  name: tce
spec:
  selector:
    stack: tce
  ports:
  - name: grpc
    port: {{ $.Values.ports.grpc }}
    protocol: TCP
  - name: p2p
    port: {{ $.Values.ports.p2p }}
    protocol: TCP
  - name: graphql
    port: {{ $.Values.ports.graphql }}
    protocol: TCP
  - name: metrics
    port: {{ $.Values.ports.metrics }}
    protocol: TCP
  clusterIP: None
{{ end }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Values.mode }}
  labels:
    app: {{ $.Values.mode }}
    stack: tce
spec:
  serviceName: tce
  podManagementPolicy: "Parallel"
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: {{ $.Values.mode }}
      stack: tce
  template:
    metadata:
      labels:
        app: {{ $.Values.mode }}
        stack: tce
    spec:
      serviceAccountName: s3-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload
                operator: In
                values:
                - topos
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "topos"
          effect: "NoExecute"
      containers:
        - name: {{ $.Values.mode }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: Always
          command: ["topos"]
          args: ["node", "up", "--name", "$(HOSTNAME)", "--no-edge-process"]
          # command: ["/bin/sh","-c"]
          # args: ["tail -f /dev/null"]
          volumeMounts:
            - mountPath: /data/node/
              name: data
          env:
            - name: RUST_LOG
              value: {{ $.Values.env.RUST_LOG }}
            - name: TOPOS_HOME
              value: {{ $.Values.env.TOPOS_HOME }}
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: grpc
              containerPort: {{ $.Values.ports.grpc }}
              protocol: TCP
            - name: p2p
              containerPort: {{ $.Values.ports.p2p }}
              protocol: TCP
            - name: graphql
              containerPort: {{ $.Values.ports.graphql }}
              protocol: TCP
            - name: metrics
              containerPort: {{ $.Values.ports.metrics }}
              protocol: TCP
      initContainers:
        - name: init
          image: amazon/aws-cli:latest
          command: ["/bin/sh","-c"]
          args: ["aws s3 cp {{ $.Values.s3.bucket }}/genesis-1-4.json /data/subnet/topos/genesis.json; aws s3 cp --recursive {{ $.Values.s3.bucket }}/node/${HOSTNAME} /data/node/${HOSTNAME}"]
          volumeMounts:
            - mountPath: /data/node/
              name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOncePod" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 1Gi
